### ISSUE TITLE
syntax error platform: Platform

### ISSUE THREAD

**Issue by patrickmamaid** [Gajotres/Ionic2ShareDataExample#1]
Hello I love your guide!

I've Followed the README.md for your guide, but I am getting a syntax error when trying to start ionic serve in:

```
./app/app.js
Module build failed: SyntaxError: /Users/patrick/ionic/ionic2test/Ionic2ShareData/app/app.js: Unexpected token (11:22)
   9 |
  10 | class MyApp {
> 11 |   constructor(platform: Platform, shareService:ShareService) {
     |                       ^
```

Then I've started again from the beginning in this snippet but it looks like the syntax issue persists:

```
patricksmacpro2015:ionic2test patrick$
patricksmacpro2015:ionic2test patrick$
patricksmacpro2015:ionic2test patrick$
patricksmacpro2015:ionic2test patrick$ npm install -g cordova ionic@beta
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic

> ionic@2.0.0-beta.19 postinstall /usr/local/lib/node_modules/ionic
> node lib/tasks/postinstall


> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall


> node-sass@3.4.2 install /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js


> node-sass@3.4.2 postinstall /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-47/binding.node ` exists.
 testing binary.
Binary is fine; exiting.

> fsevents@1.0.8 install /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.0.8 install /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
spawn-sync@1.0.15 /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync
node-sass@3.4.2 /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass
fsevents@1.0.8 /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
fsevents@1.0.8 /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
/usr/local/lib
├── cordova@6.0.0
└── ionic@2.0.0-beta.19

patricksmacpro2015:ionic2test patrick$ npm update
patricksmacpro2015:ionic2test patrick$
patricksmacpro2015:ionic2test patrick$ ionic start Ionic2ShareData blank --v2

One awesome Ionic app coming right up...

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
Installing Node Modules

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Make sure to cd into your new app directory:
  cd Ionic2ShareData

To run your app in the browser (great for initial development):
  ionic serve

To run on iOS:
  ionic run ios

To run on Android:
  ionic run android

To test your app on a device easily, try Ionic View:
  http://view.ionic.io

New! Add push notifications, update your app remotely, and package iOS and Android apps with the Ionic Platform!
https://apps.ionic.io/signup

New to Ionic? Get started here: http://ionicframework.com/docs/v2/getting-started

patricksmacpro2015:ionic2test patrick$ git clone https://github.com/Gajotres/Ionic2ShareDataExample.git
Cloning into 'Ionic2ShareDataExample'...
remote: Counting objects: 92, done.
remote: Total 92 (delta 0), reused 0 (delta 0), pack-reused 92
Unpacking objects: 100% (92/92), done.
Checking connectivity... done.
patricksmacpro2015:ionic2test patrick$ ls
Ionic2ShareData        Ionic2ShareDataExample
patricksmacpro2015:ionic2test patrick$ rm -rf Ionic2ShareData/www/
patricksmacpro2015:ionic2test patrick$ rm -rf Ionic2ShareData/app/
patricksmacpro2015:ionic2test patrick$ cp -R Ionic2ShareDataExample/www Ionic2ShareData/
patricksmacpro2015:ionic2test patrick$ cp -R Ionic2ShareDataExample/app Ionic2ShareData/
patricksmacpro2015:ionic2test patrick$ cd Ionic2ShareData/
patricksmacpro2015:Ionic2ShareData patrick$ ls
app               gulpfile.js       ionic.config.js   package.json      webpack.config.js
config.xml        hooks             node_modules      resources         www
patricksmacpro2015:Ionic2ShareData patrick$ ionic serve

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file

∆ Compiling Sass to CSS
√ Matching patterns: app/theme/app.+(ios|md|wp).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-angular/fonts/**/*.+(ttf|woff|woff2)

∆ Copying HTML
√ Matching patterns: app/**/*.html

√ Sass compilation complete

./app/app.js
Module build failed: SyntaxError: /Users/patrick/ionic/ionic2test/Ionic2ShareData/app/app.js: Unexpected token (11:22)
   9 |
  10 | class MyApp {
> 11 |   constructor(platform: Platform, shareService:ShareService) {
     |                       ^
  12 |     this.platform = platform;
  13 |     this.initializeApp();
  14 |     this.root = Home;
    at Parser.pp.raise (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:2817:8)
    at Parser.pp.expect (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:2811:33)
    at Parser.pp.parseBindingList (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:1547:12)
    at Parser.pp.parseMethod (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:1092:22)
    at Parser.pp.parseClassMethod (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:2495:8)
    at Parser.pp.parseClassBody (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:2456:10)
    at Parser.pp.parseClass (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:2339:8)
    at Parser.pp.parseStatement (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:1813:19)
    at Parser.pp.parseBlockBody (/Users/patrick/ionic/ionic2test/Ionic2ShareData/node_modules/babylon/index.js:2208:21)
 @ multi main (CLI v2.0.0-beta.19)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.2.1 Build version 7C1002



patricksmacpro2015:Ionic2ShareData patrick$
```

**Comment by billy84** [comment]
I got same issues.

SyntaxError: /Volumes/Work/.../Ionic2ShareData/app/app.js: Unexpected token (11:22) while parsing file: /Volumes/Work/Tiger/Current Work/2/NLP/Sample/Ionic2ShareData/app/app.js
------ app.js ------
import {App, Platform, Config} from 'ionic/ionic';
import {Home} from './pages/home/home';
import {ShareService} from './pages/services/ShareService';

@App({
  templateUrl: 'build/app.html',
  providers: [ShareService]
})

class MyApp {
11:  constructor(platform: Platform, shareService:ShareService) {
    this.platform = platform;
    this.initializeApp();
    this.root = Home;
    shareService.setUserName('John','Johnson');
  }

  initializeApp() {
    this.platform.ready().then(() => {
      console.log('Platform ready');
    });
  }
}

Can you help me?

**Comment by Gajotres** [comment]
The problem was in Ionic 2 beta version, this framework is ever changing. Everything is updated/working now.

**Comment by patrickmamaid** [comment]
Thanks @Gajotres
